export const TOKENS = {
  // services
  SUPABASE: 'SUPABASE',

  // use case
  CREATE_ALBUM:      'CREATE_ALBUM',
  GET_ALBUMS:        'GET_ALBUMS',
  GET_ALBUM:         'GET_ALBUM',
  GET_CURRENT_USER:  'GET_CURRENT_USER',
  GET_CARD_BY_ID:    'GET_CARD_BY_ID',
  QUERY_CARDS:       'GET_CARD',
  ADD_CARD_TO_ALBUM: 'ADD_CARD_TO_ALBUM',
  SAVE_CHANGES:      'SAVE_CHANGES',

  // repositories
  ALBUM_REPOSITORY: 'ALBUM_REPOSITORY',
  USER_REPOSITORY:  'USER_REPOSITORY',
  CARD_REPOSITORY:  'CARD_REPOSITORY',

  // presenter
  CREATE_ALBUM_PRESENTER:         'CREATE_ALBUM_PRESENTER',
  QUERY_CARDS_PRESENTER:          'QUERY_CARDS_PRESENTER',
  ADD_CARD_TO_ALBUM_PRESENTER:    'ADD_CARD_TO_ALBUM_PRESENTER',
  GET_ALBUM_VIEW_STATE_PRESENTER: 'GET_ALBUM_VIEW_STATE_PRESENTER',
  SAVE_CHANGES_PRESENTER:         'SAVE_CHANGES_PRESENTER',
  GET_CARD_BY_ID_PRESENTER:       'GET_CARD_BY_ID_PRESENTER'

} as const;

