export const TOKENS = {
  // services
  SUPABASE:    'SUPABASE',
  DECK_PARSER: 'DECK_PARSER',
  FEATURE_FLAG: 'FEATURE_FLAG',

  // finders
  CARD_FINDER: 'CARD_FINDER',
  ALBUM_FINDER: 'ALBUM_FINDER',

  // use case
  CREATE_ALBUM:      'CREATE_ALBUM',
  GET_ALBUMS:        'GET_ALBUMS',
  GET_ALBUM:         'GET_ALBUM',
  GET_CURRENT_USER:  'GET_CURRENT_USER',
  GET_AVAILABLE_SET: 'GET_AVAILABLE_SET',
  GET_CARD_BY_ID:    'GET_CARD_BY_ID',
  QUERY_CARDS:       'GET_CARD',
  ADD_CARD_TO_ALBUM: 'ADD_CARD_TO_ALBUM',
  SAVE_CHANGES:      'SAVE_CHANGES',
  DELETE_ALBUM:      'DELETE_ALBUM',
  GET_OWNED_CARDS:   'GET_OWNED_CARDS',
  CREATE_DECK:       'CREATE_DECK',
  UPDATE_DECK:       'UPDATE_DECK',
  GET_DECK:          'GET_DECK',
  LIST_USER_DECK:    'LIST_USER_DECK',
  LIST_PUBLIC_DECK:  'LIST_PUBLIC_DECK',
  IMPORT_DECK:       'IMPORT_DECK',
  GET_ALL_CARD_ALBUM: 'GET_ALL_CARD_ALBUM',

  // repositories
  ALBUM_REPOSITORY:      'ALBUM_REPOSITORY',
  USER_REPOSITORY:       'USER_REPOSITORY',
  CARD_REPOSITORY:       'CARD_REPOSITORY',
  DECK_REPOSITORY:       'DECK_REPOSITORY',
  SET_FINDER_REPOSITORY: 'SET_FINDER_REPOSITORY',

  // presenter
  CREATE_ALBUM_PRESENTER:         'CREATE_ALBUM_PRESENTER',
  QUERY_CARDS_PRESENTER:          'QUERY_CARDS_PRESENTER',
  ADD_CARD_TO_ALBUM_PRESENTER:    'ADD_CARD_TO_ALBUM_PRESENTER',
  GET_ALBUM_VIEW_STATE_PRESENTER: 'GET_ALBUM_VIEW_STATE_PRESENTER',
  GET_ALBUMS_PRESENTER:           'GET_ALBUMS_PRESENTER',
  SAVE_CHANGES_PRESENTER:         'SAVE_CHANGES_PRESENTER',
  GET_CARD_BY_ID_PRESENTER:       'GET_CARD_BY_ID_PRESENTER',
  DELETE_ALBUM_PRESENTER:         'DELETE_ALBUM_PRESENTER',
  SAVE_DECK_PRESENTER:            'SAVE_DECK_PRESENTER',
  GET_DECK_PRESENTER:             'GET_DECK_PRESENTER',
  LIST_USER_DECK_PRESENTER:       'LIST_USER_DECK_PRESENTER',
  LIST_PUBLIC_DECK_PRESENTER:     'LIST_PUBLIC_DECK_PRESENTER',
  IMPORT_DECK_PRESENTER: 'IMPORT_DECK_PRESENTER',

} as const;

