
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgtap" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."card_collection" (
    "collection_id" bigint NOT NULL,
    "card_id" bigint NOT NULL,
    "quantity" bigint NOT NULL,
    "id" bigint NOT NULL
);

ALTER TABLE "public"."card_collection" OWNER TO "postgres";

ALTER TABLE "public"."card_collection" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."card_collection_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."cards" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying DEFAULT ''::character varying NOT NULL,
    "rarity" character varying DEFAULT ''::character varying NOT NULL,
    "type" character varying DEFAULT ''::character varying NOT NULL,
    "subtype" character varying DEFAULT ''::character varying NOT NULL,
    "subtype2" character varying DEFAULT ''::character varying NOT NULL,
    "cost" character varying DEFAULT ''::character varying NOT NULL,
    "text" "text" DEFAULT ''::"text" NOT NULL,
    "image" "text" DEFAULT ''::"text" NOT NULL,
    "set" character varying DEFAULT ''::character varying NOT NULL,
    "supertype" character varying DEFAULT ''::character varying NOT NULL
);

ALTER TABLE "public"."cards" OWNER TO "postgres";

ALTER TABLE "public"."cards" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cards_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."collections_decks" (
    "id" bigint NOT NULL,
    "deck_id" bigint NOT NULL,
    "type" character varying NOT NULL
);

ALTER TABLE "public"."collections_decks" OWNER TO "postgres";

ALTER TABLE "public"."collections_decks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."collections_decks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE OR REPLACE VIEW "public"."deck_types" AS
 SELECT DISTINCT "cards"."subtype"
   FROM "public"."cards";

ALTER TABLE "public"."deck_types" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."decks" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "owner" "uuid" NOT NULL,
    "name" character varying NOT NULL,
    "likes" bigint NOT NULL,
    "type1" character varying,
    "type2" character varying,
    "isPublic" boolean DEFAULT false NOT NULL,
    "description" "text"
);

ALTER TABLE "public"."decks" OWNER TO "postgres";

ALTER TABLE "public"."decks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."decks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."cards"
    ADD CONSTRAINT "cards_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."collections_decks"
    ADD CONSTRAINT "collections_decks_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."decks"
    ADD CONSTRAINT "decks_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."card_collection"
    ADD CONSTRAINT "card_collection_card_id_fkey" FOREIGN KEY ("card_id") REFERENCES "public"."cards"("id");

ALTER TABLE ONLY "public"."card_collection"
    ADD CONSTRAINT "card_collection_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES "public"."collections_decks"("id");

ALTER TABLE ONLY "public"."decks"
    ADD CONSTRAINT "decks_owner_fkey" FOREIGN KEY ("owner") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

CREATE POLICY "Card public reads" ON "public"."cards" FOR SELECT TO "authenticated", "anon" USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."card_collection" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."collections_decks" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."decks" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable update for users based on email" ON "public"."decks" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "owner")) WITH CHECK (("auth"."uid"() = "owner"));

ALTER TABLE "public"."card_collection" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."cards" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."collections_decks" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."decks" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."card_collection" TO "anon";
GRANT ALL ON TABLE "public"."card_collection" TO "authenticated";
GRANT ALL ON TABLE "public"."card_collection" TO "service_role";

GRANT ALL ON SEQUENCE "public"."card_collection_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."card_collection_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."card_collection_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."cards" TO "anon";
GRANT ALL ON TABLE "public"."cards" TO "authenticated";
GRANT ALL ON TABLE "public"."cards" TO "service_role";

GRANT ALL ON SEQUENCE "public"."cards_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cards_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cards_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."collections_decks" TO "anon";
GRANT ALL ON TABLE "public"."collections_decks" TO "authenticated";
GRANT ALL ON TABLE "public"."collections_decks" TO "service_role";

GRANT ALL ON SEQUENCE "public"."collections_decks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."collections_decks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."collections_decks_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."deck_types" TO "anon";
GRANT ALL ON TABLE "public"."deck_types" TO "authenticated";
GRANT ALL ON TABLE "public"."deck_types" TO "service_role";

GRANT ALL ON TABLE "public"."decks" TO "anon";
GRANT ALL ON TABLE "public"."decks" TO "authenticated";
GRANT ALL ON TABLE "public"."decks" TO "service_role";

GRANT ALL ON SEQUENCE "public"."decks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."decks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."decks_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
