create table if not exists "public"."decks_temp" (
    "id" bigint generated by default as identity primary key,
    "name" text not null,
    "description" text,
    "is_public" boolean default false not null,
--     "owner" uuid references "auth"."users"("id") on delete set null,
    "owner" uuid,
    "deck_face" bigint constraint decks_deck_face_fkey references "public"."cards"("id"),
    "type_1" text,
    "type_2" text,
    "guardian" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists "public"."deck_card" (
    "deck" bigint references "public"."decks_temp"("id") on delete cascade ,
    "card" bigint references "public"."cards"("id"),
    "quantity" integer not null default 0,
    "quantity_side" integer not null default 0,
    primary key (deck, card)
);

-- MOVE DECKS
insert into "public"."decks_temp" (id, name, description, is_public, owner, type_1, type_2, guardian, created_at, updated_at)
select
    c.id,
    c.name,
    c.description,
    c.is_public,
    c.owner,
    c.type1,
    c.type2,
    NULL,
    c.created_at,
    c.updated_at
from "public"."decks" c;

insert into "public"."deck_card" (deck, card, quantity, quantity_side)
select
    cc.deck_id,
    ccard.card_id,
    sum(case when cc.type in ('DECK', 'TREASURE') then ccard.quantity else 0 end ) as quantity,
    sum(case when cc.type = 'SIDE' then ccard.quantity else 0 end ) as quantity_side
from "public"."collections_decks" cc
join "public"."card_collection" ccard on cc.id = ccard.collection_id
group by cc.deck_id, ccard.card_id;

drop table if exists "public"."card_collection" cascade;
drop table if exists "public"."collections_decks" cascade;
drop table if exists "public"."decks" cascade;
alter table "public"."decks_temp" rename to "decks";
