create table if not exists "public"."albums" (
    "id" bigint generated by default as identity primary key,
    "name" text not null,
    "total" int not null,
    "current" int not null,
    "sets" text[] not null,
    "owner" uuid not null
);

create table if not exists "public"."album_cards" (
    "id" bigint generated by default as identity primary key,
    "album_id" int not null REFERENCES "public"."albums"(id) ON DELETE CASCADE,
    "card_id" int not null REFERENCES "public"."cards"(id) ON DELETE CASCADE,
    "quantity" int not null default 0,
    UNIQUE(album_id, card_id)
);

create table if not exists "public"."album_tag" (
    "id" bigint generated by default as identity primary key,
    "name" text not null,
    "album_id" bigint not null REFERENCES "public"."albums"(id) ON DELETE CASCADE,
    UNIQUE(album_id, name)
);

create table if not exists "public"."album_card_tags" (
    "id" bigint generated by default as identity primary key,
    "album_card_id" bigint REFERENCES "public"."album_cards"(id) ON DELETE CASCADE,
    "tag_id" bigint REFERENCES "public"."album_tag"(id) ON DELETE CASCADE,
    "quantity" int not null default 0
);
