create table if not exists "public"."albums" (
    "id" bigint generated by default as identity primary key,
    "name" text not null,
    "total" int not null,
    "current" int not null check("current" >= 0),
    "sets" text[] not null,
    "owner" uuid not null
);

create table if not exists "public"."album_tags" (
    "id" bigint generated by default as identity primary key,
    "name" text not null,
    "album_id" bigint not null REFERENCES "public"."albums"(id) ON DELETE CASCADE,
    UNIQUE(album_id, name)
);

create table if not exists "public"."album_cards" (
    "card_id" bigint REFERENCES "public"."cards"(id) ON DELETE CASCADE,
    "album_id" bigint REFERENCES "public"."albums"(id) ON DELETE CASCADE,
    "tag_id" bigint REFERENCES "public"."album_tags"(id) ON DELETE CASCADE,
    "quantity" int not null default 0 check("quantity" <= 10),
    PRIMARY KEY ("card_id", "tag_id", "album_id")
);

CREATE VIEW user_cards_totals AS
SELECT
    a.owner,
    ac.card_id,
    SUM(ac.quantity) AS total_quantity
FROM album_cards ac
         JOIN albums a ON ac.album_id = a.id
GROUP BY a.owner, ac.card_id;

create or replace view user_cards_by_album AS
select
    ac.album_id,
    ac.card_id,
    c.*
from "public"."album_cards" ac
         join "public"."cards" c ON c.id = ac.card_id
group by ac.album_id, ac.card_id, c.id;
